import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

// Load .env.local manually because Node doesn't do it automatically
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');
dotenv.config({ path: path.join(rootDir, '.env.local') });

const configContent = `// Generated by scripts/generate-config.js
const config = {
    supabaseUrl: "${process.env.SUPABASE_URL || ''}",
    supabaseKey: "${process.env.SUPABASE_ANON_KEY || ''}"
};

export default config;
`;

const targetPath = path.join(process.cwd(), 'public', 'js', 'config.js');

// Check for Vercel environment
const isVercel = process.env.VERCEL === '1';

if (process.env.SUPABASE_URL && process.env.SUPABASE_ANON_KEY) {
    fs.writeFileSync(targetPath, configContent);
    console.log('✅ Generated public/js/config.js from environment variables.');
} else {
    if (isVercel) {
        console.error('❌ Error: SUPABASE_URL and SUPABASE_ANON_KEY are required in Vercel Environment Variables.');
        process.exit(1); // Fail the build
    } else {
        console.log('⚠️  Local dev: SUPABASE_URL not found. Skipping config generation (assuming config.js exists or will be manual).');
    }
}
