import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

// Load .env.local manually because Node doesn't do it automatically
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');
dotenv.config({ path: path.join(rootDir, '.env.local') });

const configContent = `// Generated by scripts/generate-config.js
const config = {
    supabaseUrl: "${process.env.SUPABASE_URL || ''}",
    supabaseKey: "${process.env.SUPABASE_ANON_KEY || ''}"
};

export default config;
`;

const targetPath = path.join(process.cwd(), 'public', 'js', 'config.js');

// Only overwrite if env vars exist (to avoid breaking local dev if env is missing)
if (process.env.SUPABASE_URL) {
    fs.writeFileSync(targetPath, configContent);
    console.log('✅ Generated public/js/config.js from environment variables.');
} else {
    console.log('⚠️  SUPABASE_URL not found in environment. Skipping config generation.');
}
